name: flutter_boilerplate
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #for use the phone storage preferences
  shared_preferences: ^2.0.10
  flutter_secure_storage: ^5.0.2

  #for firebase cloud firestore
  cloud_firestore: ^3.1.4
  #for open any url
  url_launcher: ^6.0.17
  #for know packages all infos
  package_info_plus: ^1.3.0
  #for firebase remote config
  firebase_remote_config: ^1.0.2

  #for toast
  fluttertoast: ^8.0.8
  flutter_styled_toast: ^2.0.0

  #for firebase analytics
  firebase_analytics: ^9.0.2
  #for firebase crashlatics
  firebase_crashlytics: ^2.4.3
  #for firebase dynamic links
  firebase_dynamic_links: ^4.0.2
  #for firebase messaging
  firebase_messaging: ^11.2.3
  #for local notification
  flutter_local_notifications: ^9.1.5
  #for location service
  location: ^4.3.0
  geolocator: ^8.0.0

  #for checking internet connection
  connectivity_plus: ^2.1.0

  #for date time
  intl: ^0.17.0
  #for prints beautiful logs.
  logger: ^1.1.0
  #for finds time duration.
  timeago: ^3.1.0

  #for http connection
  dio: ^5.0.3

  #for responsiveness
  flutter_screenutil: ^5.0.1

  #for local database
  sqflite: ^2.0.1

  #image loader
  cached_network_image: ^3.2.0

  #for path selection
  path_provider: ^2.0.8

  #for permission
  permission_handler: ^8.3.0

  #for finding device info
  device_info_plus: ^3.1.1

  #for icloud storage
  icloud_storage: ^0.2.1

  #for loading effects
  shimmer: ^2.0.0

  #for google fonts
  google_fonts: ^2.1.0

  #for local storage
  get_storage: ^2.0.3

  #for audio
  just_audio: ^0.9.18



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

